# generated-from:9c71c5b7640c2e2b0d66625a6bcb27fd6917e5aa8fcb9145421ac1d8f64c92dc DO NOT REMOVE, DO UPDATE

version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
    - "3106:3306"
    environment: 
    - MYSQL_DATABASE=slack-integration
    - MYSQL_USER=slack-integration
    - MYSQL_PASSWORD=slack-integration
    - MYSQL_ROOT_PASSWORD=root
    networks:
    - intranet
    tmpfs: # Run this mysql in memory as its used for testing
      - /var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
    - intranet
    tmpfs: # Run this mysql in memory as its used for testing
      - /tmp/zookeeper

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: ""
      PORT_COMMAND: "docker port $$(hostname) 9092/tcp | cut -d: -f2"
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - intranet
    tmpfs: # Run this mysql in memory as its used for testing
      - /tmp/kafka-logs

networks:
    intranet:
