name: Publish Docker

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    name: Yarn Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }} # sets ref to the last commit hash

      - name: Install Node and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Docker Login
        run: |+
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker
        run: make release
